name: flutter_app_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  fl_chart: ^0.70.2
  flutter_secure_storage: ^9.2.4
  smooth_page_indicator: ^1.2.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  vibration: ^3.1.3
  intl: ^0.19.0
  easy_localization: ^3.0.7+1
  json_annotation: ^4.9.0
  collection: ^1.19.1
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0


dependency_overrides:
  custom_lint_visitor: 1.0.0+7.3.0


flutter:
  uses-material-design: true
  assets:
    - resources/langs/

  # To main resources to your application, main an resources section, like this:
  # resources:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding resources from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To main custom fonts to your application, main a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
#easy_localization:
#  path: lib/core/resources/langs/
#  output: lib/generated/lib/l10n
#  filename: locale_keys.g.dart
#  codegen_format: keys